#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi



function source_if_exists() {
    if [[ -s $1 ]]; then
        source $1
    fi
}

source_if_exists $HOME/.yodle-dev-shell-utils/conf/sh/all

# put personal aliases in this file so they aren't tracked in version control
source_if_exists $HOME/.alias

# put personal config in this file so they aren't tracked in version control
source_if_exists $HOME/.local_zshrc

export PATH=/workspace/bin:$HOME/.yodle-dev-shell-utils/bin:$PATH

export KEYTIMEOUT=1
